# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:6qCroasNk2GK7CaeL6MACLQQTuf6AL+DoEX5PhFe4eWv4OazvUHpFhDVkb8Q9WfNNMd0kUT1zsfKrACZyZNEzE3faD0bDFU5gUtjSPqLroXLF+SS8Hp6l9PjTmXRgEdia+yrXbHjQCd5d1hxI7Ui29Nst+/KoW7HcNlLNzQV/2UVl7p/fODcO7/lvUMLchysGsQ1OvTXvmpQ/rJ+fOnYgbIfLJzi6lXqIqu+1qlwf7+qR6JQfw==,iv:6Fqk65CQhCt6D9EAiWgXc2iVRKm7/07WcxgVVrxWX7M=,tag:0iMU71YSfKG1A04aGDT7gg==,type:str]
sops:
  age:
    - recipient: age16w08l782hpmk9jsfu7cxkxh2w3djr8e4aewz4h68dkpat37vvvdquw24qt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWlBnSEF5TnZBcDhqbkZv
        Qjd3YUhoSzNzTEVWMEtpQ3l1NUJieE9WYUFVCnlSd29RdTZVOXVIcGRyRGljdmJz
        Z01zcTZiMVdHVjhCRjlqMUhVL2V3U1UKLS0tIGhOS3Q2bWhjNzhQRUY1WWRVdS9z
        L0FacnNzb3FjZVFHNUc3TUVOa1F1NzAKUr8K+UQfseGG6+nEyu1ega0NDKvwteD3
        5BGAzSM5QkdPIv4bhJ28/Gu4GoZ5k8yy0ckGUoMpFXpGgQ8PTpWGtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T21:31:56Z"
  mac: ENC[AES256_GCM,data:DtL5TD/IKrLh5T9hr4ahIH4uRtgSbP9Q7VW8Ny6Jkc29mZ2PZRFerQShF1RfTgOLNzcoFt46cTAJIOjqn4gZDC0ClOZQRalPtCDunOq+ze0FHq/6DbhvsqoEb2RBJSFN5x2rRuKBuqkxWb7EIf7QBfehoqo8YD4I+O+eYBXs/dc=,iv:PCezPfzQ+LoYoHZ7yI5o3n09D2ucDJwYYkDR27KEa9Y=,tag:2JJWaCxKGP8djb9hpkYMfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
