# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:FOOqJae5eamKpwwK5MBW/pG+B0ysHR73LJTozxPQGoo=,iv:yZLFGn3qQAhILtXztas+2rvuRgHCBNu4ZmwLLcSEaKY=,tag:zCE6GSEmx8tBF20Og16PEQ==,type:str]
sops:
  age:
    - recipient: age16w08l782hpmk9jsfu7cxkxh2w3djr8e4aewz4h68dkpat37vvvdquw24qt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZRjJxWGhxSzdwZnVJWWw2
        aDkvN3FiMjNFTFN3blF5MjlqQmROMitzRVFjClMrcTY0YVFRSDdnbFJjTnBXRnk0
        TkVOYVFnNlBReGdtcGw5V0I0YmhXVEUKLS0tIDBlSXFaa1ZGMWkxMDkzbHVqMUtC
        VENub2tMbm5mcGtLSit0djZNWm1UOXMKd+1mBk5wRBYl1oDLxfEKW3u1TCxaYs/M
        hP2LUa8LeW05WHRKh7NYeBKE3usZuEyhVKEusHwXx7Wd5sl5KGjDEA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T21:31:56Z"
  mac: ENC[AES256_GCM,data:tdaIvWsWrMRtn9ALWZSjszDnGPBBzefpV5l6xRRaLzcPO4SyHDQBZZYMlxF+5c04QPyIygty6dWEdWvl+PWjR5T+zMMBUWZszrVd4pdfj/qS/NHpExFJU4CqkoZ1iNngQNEh1/J7BoYKW02kp5eHR82aw9aj+3pcxDh7av6JYKA=,iv:vGf8d9XwlZZ819CR+K9J01rhxcAbyNRjktWZpHcnjN4=,tag:YY/p8e8HwWSKFzSuROzdJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
