---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lyrion-music-server
spec:
  ingressClassName: internal
  rules:
    - host: "lms.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lyrion-music-server
                port:
                  number: 9000