---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lyrion-music-server
  annotations:
    external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
spec:
  ingressClassName: external
  rules:
    - host: "lms.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: lyrion-music-server
                port:
                  number: 9000