# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:9qvx6iUDrRawbT32BJGeN5voMVB/lkNud95GlSr9iYBV142ehq+0IA==,iv:sFtQzbqAmFPfgkvl0/XyfTB8/X5n/n31/yO7/c5RgTk=,tag:Nv+J1ByKZC0Pjy/JCrP0Mw==,type:str]
sops:
  age:
    - recipient: age16w08l782hpmk9jsfu7cxkxh2w3djr8e4aewz4h68dkpat37vvvdquw24qt
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnLzhBWWJ1TkRhc0Y4WFNn
        WTlxWk9qVDJ0cFdYT1VaMnI4SDRQVzhhK2xNCnN3T1hEeUwyN0xwbFl2RGhlU1Ax
        ZmJaVFdaMGl2QmdEYmFVUU1qWEpRZ0EKLS0tIC9OQ0hKM1RoVjVma3Y1Z1J6OEMy
        QlowZEg0K3NBNnRjYVRjSUtnWTc3ZDQKz/C6YnitjbCViTmzJCsU+9UAdoW4WJlF
        g7wRzqWCpijzIl3d/NU9EjvhTVNU/skhRcy+0VpQJG8DF+FJPj3+fQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-18T21:31:56Z"
  mac: ENC[AES256_GCM,data:8OGfeXwNLsAC3IM7zQ62m97V98bmbgo7zeyzal02vEqEMj9Hr8rzwQeg7S77tWgakSy3IItXNLW+B9qP0gZASlzxxvbFsEpzWtW0zREaUphMGI1+2wpslnmBDsH0goESPcs1DvFhU4TRQjhjj4F4CBOdK6zNPOhYNAgYvgXsFT8=,iv:KkojlzGP5jmrjMPtZz7M3U6bb10LqI1lQDrVtQqos2o=,tag:OfKR7Js9w57V/fzu3BFhtQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
