# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://192.168.178.140:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "192.168.178.140"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "master-1"
    ipAddress: "192.168.178.133"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:d4:2d:c1"
        dhcp: false
        addresses:
          - "192.168.178.133/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.178.1"
        mtu: 1500
        vip:
          ip: "192.168.178.140"
  - hostname: "worker-1"
    ipAddress: "192.168.178.134"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:71:72:33"
        dhcp: false
        addresses:
          - "192.168.178.134/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.178.1"
        mtu: 1500
  - hostname: "worker-2"
    ipAddress: "192.168.178.135"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/376567988ad370138ad8b2698212367b8edcb69b5fd68c80be1f2ec7d603b4ba
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:45:41:19"
        dhcp: false
        addresses:
          - "192.168.178.135/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "192.168.178.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

